[versions]
agp = "8.7.0"
kotlin = "1.9.23"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.2.1"
lifecycleRuntimeKtx = "2.8.6"
cardview = "1.0.0"
recyclerview = "1.3.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-camera-core = "androidx.camera:camera-core:1.3.4"
androidx-camera-camera2 = "androidx.camera:camera-camera2:1.3.4"
androidx-camera-lifecycle = "androidx.camera:camera-lifecycle:1.3.4"
androidx-camera-view = "androidx.camera:camera-view:1.3.4"
google-mlkit-text-recognition = "com.google.mlkit:text-recognition:16.0.1"
androidx-room-runtime = "androidx.room:room-runtime:2.6.1"
androidx-room-compiler = "androidx.room:room-compiler:2.6.1"
androidx-room-ktx = "androidx.room:room-ktx:2.6.1"
gson = "com.google.code.gson:gson:2.10.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
